### ISSUE TITLE
Ska inte finns någon console.log i den slutgiltiga koden

### ISSUE THREAD

**Issue by glajan** [CharlotteH86/Calculator-1#1]
https://github.com/CharlotteH86/Calculator-1/blob/7ca2f8a78055502848d33d215ee44699777d5f2b/script.js#L17

**Comment by CharlotteH86** [comment]
Ett antal console.log bortplockade och kommentarer tillagda. Console.log användes i guiden för att man skulle hålla kolla och se så att allt fungerade under processen.
